ALTER TABLE hunting
    RENAME COLUMN tid TO `checked_at`,
    ADD `started_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD `last_reward_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP;
